# syntax = docker/dockerfile:1
# Auto Generated by Fly.io

# Adjust NODE_VERSION as desired
ARG NODE_VERSION=18.15.0
FROM node:${NODE_VERSION}-slim as base

LABEL fly_launch_runtime="NodeJS"

# NodeJS app lives here
WORKDIR /app

# Set production environment
ENV NODE_ENV=production

RUN --mount=type=secret,id=DISCORD_BOT_TOKEN \
    DISCORD_BOT_TOKEN="$(cat /run/secrets/DISCORD_BOT_TOKEN)"
    
RUN --mount=type=secret,id=MONGO_URI \
    MONGO_URI="$(cat /run/secrets/MONGO_URI)" \ 

# Throw-away build stage to reduce size of final image
FROM base as build

# Install packages needed to build node modules
RUN apt-get update -qq && \
    apt-get install -y python-is-python3 pkg-config build-essential 

# Install node modules
COPY --link package.json package-lock.json ./
RUN npm install --legacy-peer-deps

# Copy application code
COPY --link . .

# Remove development dependencies
RUN npm prune --production

# Final stage for app image
FROM base

# Copy built application
COPY --from=build /app /app

# Start the server by default, this can be overwritten at runtime
CMD [ "npm", "run", "start" ]
