name: Fly.io Deployment (Prod)
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Fly.io Deployment (Prod)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl secrets set DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} MONGO_URI=${{ secrets.MONGO_URI }}
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}